# Generated by Django 3.1.2 on 2020-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('st', 'https://slo-tech.com/'), ('mn', 'https://www.monitor.si/')], max_length=3)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(max_length=40)),
                ('summary', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
