# Generated by Django 3.1.2 on 2020-12-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.URLField(),
        ),
    ]
