# Generated by Django 3.1.2 on 2020-12-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201218_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
