# Generated by Django 3.1.2 on 2020-12-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201221_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='saved_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='page',
            field=models.CharField(choices=[('st', 'Slo-tech'), ('mn', 'Monitor')], max_length=3),
        ),
    ]
