# Generated by Django 3.1.2 on 2020-12-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201224_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='saved_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
