# Generated by Django 3.1.2 on 2020-12-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201224_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='saved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
