# Generated by Django 3.1.2 on 2021-02-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210224_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.statistic'),
        ),
    ]
