# Generated by Django 3.1.2 on 2021-02-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_story_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='stats',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
