# Generated by Django 3.1.2 on 2021-03-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210224_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='slug',
            new_name='url',
        ),
    ]
